/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as DashboardIndexImport } from "./routes/dashboard/index";

// Create Virtual Routes

const DashboardBmrMifflinLazyImport = createFileRoute(
  "/dashboard/bmr-mifflin"
)();

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRoute,
} as any);

const DashboardBmrMifflinLazyRoute = DashboardBmrMifflinLazyImport.update({
  id: "/dashboard/bmr-mifflin",
  path: "/dashboard/bmr-mifflin",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/dashboard/bmr-mifflin.lazy").then((d) => d.Route)
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/bmr-mifflin": {
      id: "/dashboard/bmr-mifflin";
      path: "/dashboard/bmr-mifflin";
      fullPath: "/dashboard/bmr-mifflin";
      preLoaderRoute: typeof DashboardBmrMifflinLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard/bmr-mifflin": typeof DashboardBmrMifflinLazyRoute;
  "/dashboard": typeof DashboardIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard/bmr-mifflin": typeof DashboardBmrMifflinLazyRoute;
  "/dashboard": typeof DashboardIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/dashboard/bmr-mifflin": typeof DashboardBmrMifflinLazyRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard/bmr-mifflin" | "/dashboard";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard/bmr-mifflin" | "/dashboard";
  id: "__root__" | "/" | "/dashboard/bmr-mifflin" | "/dashboard/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardBmrMifflinLazyRoute: typeof DashboardBmrMifflinLazyRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardBmrMifflinLazyRoute: DashboardBmrMifflinLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/bmr-mifflin",
        "/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/bmr-mifflin": {
      "filePath": "dashboard/bmr-mifflin.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
